package model

// AzureCloudRegion : AzureCloudRegion model
type AzureCloudRegion string

// List of possible AzureCloudRegion values
const (
	AzureCloudRegion_US_WEST             AzureCloudRegion = "US_WEST"
	AzureCloudRegion_US_WEST2            AzureCloudRegion = "US_WEST2"
	AzureCloudRegion_US_CENTRAL          AzureCloudRegion = "US_CENTRAL"
	AzureCloudRegion_US_EAST             AzureCloudRegion = "US_EAST"
	AzureCloudRegion_US_EAST2            AzureCloudRegion = "US_EAST2"
	AzureCloudRegion_US_NORTH_CENTRAL    AzureCloudRegion = "US_NORTH_CENTRAL"
	AzureCloudRegion_US_SOUTH_CENTRAL    AzureCloudRegion = "US_SOUTH_CENTRAL"
	AzureCloudRegion_US_WEST_CENTRAL     AzureCloudRegion = "US_WEST_CENTRAL"
	AzureCloudRegion_CANADA_CENTRAL      AzureCloudRegion = "CANADA_CENTRAL"
	AzureCloudRegion_CANADA_EAST         AzureCloudRegion = "CANADA_EAST"
	AzureCloudRegion_BRAZIL_SOUTH        AzureCloudRegion = "BRAZIL_SOUTH"
	AzureCloudRegion_BRAZIL_SOUTHEAST    AzureCloudRegion = "BRAZIL_SOUTHEAST"
	AzureCloudRegion_EUROPE_NORTH        AzureCloudRegion = "EUROPE_NORTH"
	AzureCloudRegion_EUROPE_WEST         AzureCloudRegion = "EUROPE_WEST"
	AzureCloudRegion_UK_SOUTH            AzureCloudRegion = "UK_SOUTH"
	AzureCloudRegion_UK_WEST             AzureCloudRegion = "UK_WEST"
	AzureCloudRegion_FRANCE_CENTRAL      AzureCloudRegion = "FRANCE_CENTRAL"
	AzureCloudRegion_FRANCE_SOUTH        AzureCloudRegion = "FRANCE_SOUTH"
	AzureCloudRegion_SWITZERLAND_NORTH   AzureCloudRegion = "SWITZERLAND_NORTH"
	AzureCloudRegion_SWITZERLAND_WEST    AzureCloudRegion = "SWITZERLAND_WEST"
	AzureCloudRegion_GERMANY_NORTH       AzureCloudRegion = "GERMANY_NORTH"
	AzureCloudRegion_GERMANY_WESTCENTRAL AzureCloudRegion = "GERMANY_WESTCENTRAL"
	AzureCloudRegion_NORWAY_WEST         AzureCloudRegion = "NORWAY_WEST"
	AzureCloudRegion_NORWAY_EAST         AzureCloudRegion = "NORWAY_EAST"
	AzureCloudRegion_ASIA_EAST           AzureCloudRegion = "ASIA_EAST"
	AzureCloudRegion_ASIA_SOUTHEAST      AzureCloudRegion = "ASIA_SOUTHEAST"
	AzureCloudRegion_JAPAN_EAST          AzureCloudRegion = "JAPAN_EAST"
	AzureCloudRegion_JAPAN_WEST          AzureCloudRegion = "JAPAN_WEST"
	AzureCloudRegion_AUSTRALIA_EAST      AzureCloudRegion = "AUSTRALIA_EAST"
	AzureCloudRegion_AUSTRALIA_SOUTHEAST AzureCloudRegion = "AUSTRALIA_SOUTHEAST"
	AzureCloudRegion_AUSTRALIA_CENTRAL   AzureCloudRegion = "AUSTRALIA_CENTRAL"
	AzureCloudRegion_AUSTRALIA_CENTRAL2  AzureCloudRegion = "AUSTRALIA_CENTRAL2"
	AzureCloudRegion_INDIA_CENTRAL       AzureCloudRegion = "INDIA_CENTRAL"
	AzureCloudRegion_INDIA_SOUTH         AzureCloudRegion = "INDIA_SOUTH"
	AzureCloudRegion_INDIA_WEST          AzureCloudRegion = "INDIA_WEST"
	AzureCloudRegion_KOREA_CENTRAL       AzureCloudRegion = "KOREA_CENTRAL"
	AzureCloudRegion_KOREA_SOUTH         AzureCloudRegion = "KOREA_SOUTH"
	AzureCloudRegion_UAE_CENTRAL         AzureCloudRegion = "UAE_CENTRAL"
	AzureCloudRegion_UAE_NORTH           AzureCloudRegion = "UAE_NORTH"
	AzureCloudRegion_SOUTHAFRICA_NORTH   AzureCloudRegion = "SOUTHAFRICA_NORTH"
	AzureCloudRegion_SOUTHAFRICA_WEST    AzureCloudRegion = "SOUTHAFRICA_WEST"
	AzureCloudRegion_CHINA_NORTH         AzureCloudRegion = "CHINA_NORTH"
	AzureCloudRegion_CHINA_EAST          AzureCloudRegion = "CHINA_EAST"
	AzureCloudRegion_CHINA_NORTH2        AzureCloudRegion = "CHINA_NORTH2"
	AzureCloudRegion_CHINA_EAST2         AzureCloudRegion = "CHINA_EAST2"
	AzureCloudRegion_GERMANY_CENTRAL     AzureCloudRegion = "GERMANY_CENTRAL"
	AzureCloudRegion_GERMANY_NORTHEAST   AzureCloudRegion = "GERMANY_NORTHEAST"
	AzureCloudRegion_GOV_US_VIRGINIA     AzureCloudRegion = "GOV_US_VIRGINIA"
	AzureCloudRegion_GOV_US_IOWA         AzureCloudRegion = "GOV_US_IOWA"
	AzureCloudRegion_GOV_US_ARIZONA      AzureCloudRegion = "GOV_US_ARIZONA"
	AzureCloudRegion_GOV_US_TEXAS        AzureCloudRegion = "GOV_US_TEXAS"
	AzureCloudRegion_GOV_US_DOD_EAST     AzureCloudRegion = "GOV_US_DOD_EAST"
	AzureCloudRegion_GOV_US_DOD_CENTRAL  AzureCloudRegion = "GOV_US_DOD_CENTRAL"
)
