package model


// PerTitleFixedResolutionAndBitrateConfigurationMode : PerTitleFixedResolutionAndBitrateConfigurationMode model
type PerTitleFixedResolutionAndBitrateConfigurationMode string

// List of possible PerTitleFixedResolutionAndBitrateConfigurationMode values
const (
    PerTitleFixedResolutionAndBitrateConfigurationMode_LAST_CALCULATED_BITRATE PerTitleFixedResolutionAndBitrateConfigurationMode = "LAST_CALCULATED_BITRATE"
    PerTitleFixedResolutionAndBitrateConfigurationMode_MINIMUM PerTitleFixedResolutionAndBitrateConfigurationMode = "MINIMUM"
    PerTitleFixedResolutionAndBitrateConfigurationMode_MAXIMUM PerTitleFixedResolutionAndBitrateConfigurationMode = "MAXIMUM"
    PerTitleFixedResolutionAndBitrateConfigurationMode_AVERAGE PerTitleFixedResolutionAndBitrateConfigurationMode = "AVERAGE"
)


