package model

// StreamPerTitleSettings model
type StreamPerTitleSettings struct {
	// Settings for PER_TITLE_TEMPLATE_FIXED_RESOLUTION_AND_BITRATE mode
	FixedResolutionAndBitrateSettings *StreamPerTitleFixedResolutionAndBitrateSettings `json:"fixedResolutionAndBitrateSettings,omitempty"`
	// This factor is used to calculate the maxBitrate of the codec configuration for the generated representation as a multiple of the targetBitrate(generated by Per-Title algorithm). This value will take precedence over the 'codecMaxBitrateFactor' from the pertitleStartConfiguration. This value will only have an impact on streams with h264 or h265 video configurations.
	CodecMaxBitrateFactor *float64 `json:"codecMaxBitrateFactor,omitempty"`
	// This factor is used to calculate the bufsize of the codec configuration for the generated representations as a multiple of the targetBitrate(generated by Per-Title algorithm). This value will take precedence over the 'codecBufsizeFactor' from the pertitleStartConfiguration.. This value will only have an impact on streams with h264 or h265 video configurations.
	CodecBufsizeFactor *float64 `json:"codecBufsizeFactor,omitempty"`
}
